# DataRoot University DS100 Test #2
На проходження тесту виділяється 100 і одна хвилина.

## Python

### 1.  Реалізуйте функцію для видалення дублікатів зі списку списків:
У відповідь вивести результат роботи ф-ції для наступного списку:
```
[[10, 20], [40], [30, 56, 25], [10, 20], [33], [40], [42], [10, 42], [42]]
```


```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [1]:
def dupl_del(lst):
    res = []
    for item in lst:
        if item not in res:
            res.append(item)
    return res

example = [[10, 20], [40], [30, 56, 25], [10, 20], [33], [40], [42], [10, 42], [42]]
print(dupl_del(example))

[[10, 20], [40], [30, 56, 25], [33], [42], [10, 42]]


### 2.  Реалізуйте функцію str -> dict, таку, що ключем dict є символ строки, а значенням - його кількість в початковій str:
У відповідь вивести результат роботи ф-ції для наступної строки:
```"DataRoot University DS100 Test #2"```

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [2]:
def str_to_dict(string):
    str_dict = {}
    for char in string:
        if char not in str_dict:
            str_dict[char] = 1
        else:
            str_dict[char] += 1
    return str_dict

example = "DataRoot University DS100 Test #2"
print(str_to_dict(example))

{'D': 2, 'a': 2, 't': 4, 'R': 1, 'o': 2, ' ': 4, 'U': 1, 'n': 1, 'i': 2, 'v': 1, 'e': 2, 'r': 1, 's': 2, 'y': 1, 'S': 1, '1': 1, '0': 2, 'T': 1, '#': 1, '2': 1}


### 3. Реалізуйте функцію, яка приймає два параметри: к-сть голів та к-сть ніг. За допомогою цієї функції вирішити наступну проблему: ми нарахували 35 голів та 94 ніг серед курей та кроликів на фермі. Скільки кроликів і скільки курей ми маємо?

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 7хв
```

In [25]:
import numpy as np

def animals(heads, legs):
    #4*rabbits + 2*chickens = heads
    #rabbits + chickens = legs
    
    A = np.mat([[4, 2], [1, 1]], dtype = int)
    b = np.array([legs, heads], dtype = int)
    
    return np.linalg.solve(A, b)
    
rabbits, chickens = animals(35, 94)
print('Rabbits = {0}\nChickens = {1}'.format(rabbits, chickens))

Rabbits = 12.0
Chickens = 23.0


### 4. Реалізуйте клас під назвою Circle, побудований за радіусом та містить два способи, які обчислюють площу та периметр.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [21]:
import math

class Circle():
    def __init__(self, r):
        self.r = r
    def square(self):
        return math.pi*math.pow(self.r, 2)
    def perimeter(self):
        return 2*math.pi*self.r

12.566370614359172 12.566370614359172


### 5.  Реалізуйте декоратор, який логує аргументи функцій та повернене значення кожного виклику. Необхідно виводити як позиційні(```*args```), так й іменовані аргументи(```**kwargs```):

Приклад застосування вашого декоратору в результаті:
```
>>> @log
... def func(*args):
...   return len(args)
>>> func(4, 4, 4)
you called func(4, 4, 4)
it returned 3
3
```

```
```
```
```
```
```
```
Максимальна оцінка: 4 бали
Рекомендований час: 15хв
```

## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Розв'яжіть систему рівнянь:


\begin{equation*}
 \begin{cases}
   x + y - z + 2 = 0
   \\
   3x - y + 2z - 9 = 0
   \\
   4x + 4y - 3z + 5 = 0
 \end{cases}
\end{equation*}

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв

```

In [24]:
A = np.mat([[1, 1, -1], [3, -1, 2], [4, 4, -3]])
b = np.array([-2, 9, -5])

x, y, z = np.linalg.solve(A, b)
print('x = {0}\ny = {1}\nz = {2}'.format(x, y, z))

 x = 1.0
 y = -0.0
 z = 3.0


### 7. Дана матриця:
\begin{align}
A = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}
Знайти:

#### 7.1. Транспоновану: $A^{-1}$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [31]:
A = np.mat([[17, 24, 1, 8, 15],
             [23, 5, 7, 14, 16], 
             [4, 6, 13, 20, 22],
             [10, 12, 19, 21, 3],
             [11, 18, 25, 2, 9]])

A_T = A.T
print(A_T)

[[17 23  4 10 11]
 [24  5  6 12 18]
 [ 1  7 13 19 25]
 [ 8 14 20 21  2]
 [15 16 22  3  9]]


#### 7.2. Детермінант: $\det A$

```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [32]:
det_A = np.linalg.det(A)
print(det_A)

5070000.0


#### 7.3. Слід: $\DeclareMathOperator{\tr}{Tr}\tr A$
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [34]:
trace_A = np.trace(A)
print(trace_A)

65


#### 7.4. Доказати, що матриця А є магічним квадратом.
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [60]:
is_magic = False

row_sums = []
col_sums = []

for i in range(len(A)):
    row_sums.append(int(sum(A[i, :].reshape(len(A), 1))))
    col_sums.append(int(sum(A[:, i])))
diag_sum = np.trace(A)

an_diag_sum = 0
for i in range(len(A)):
    an_diag_sum += A[i, i]
    
print("Array of row's sums: {0}\n\nArray of column's sums: {1}\n\nSum of diagonal elements: {2}\n\nSum of another diagonal elements: {3}".format(row_sums, col_sums, diag_sum, an_diag_sum))

if row_sums == col_sums and diag_sum == an_diag_sum and diag_sum in row_sums:
    is_magic = True
    
if is_magic:
    print("The matrix is magic")

Array of row's sums: [65, 65, 65, 65, 65]

Array of column's sums: [65, 65, 65, 65, 65]

Sum of diagonal elements: 65

Sum of another diagonal elements: 65
The matrix is magic


### Pandas

### 8. Розглянемо наступний словник ```data``` та список ```labels```:

In [118]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#### 8.1. Створіть ```DataFrame``` ```df``` з даних словника ```data``` з індексами зі списку ```labels```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [119]:
import pandas as pd

df = pd.DataFrame(data, labels)

#### 8.2. Відобрзіть базову інформацію про цей ```DataFrame``` та його дані:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
age         8 non-null float64
animal      10 non-null object
priority    10 non-null object
visits      10 non-null int64
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


#### 8.3. Поверніть перші 3 рядки ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [121]:
df[:3]

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2

#### 8.4. Виберіть стовпчики ```"animal"``` та ```"age"``` з ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [122]:
df.loc[:, ["animal", "age"]]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

#### 8.5 Виберіть дані з рядків ```[3, 4, 8]``` та стовпчиків ```['animal', 'age']```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [123]:
df.loc[['c', 'd', 'h'], ['animal', 'age']]

animal  age
c  snake  0.5
d    dog  NaN
h    cat  NaN

#### 8.6. Виберіть лише ті рядки, в яких к-сть візитів більша ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [124]:
df.loc[df["visits"] > 3]

Empty DataFrame
Columns: [age, animal, priority, visits]
Index: []

In [134]:
df[df["age"] == None]

Empty DataFrame
Columns: [age, animal, priority, visits]
Index: []

#### 8.7. Виберіть рядки, де вік відсутній, тобто ```NaN```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

In [136]:
df[[:], df['animal'] == 'cat' and df['age'] < 3]

SyntaxError: invalid syntax (<ipython-input-136-231ea59fe767>, line 1)

#### 8.8. Виберіть рядки з котами, вік яких менше ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 8.9. Підрахуйте середній вік для кожного з типів тварин:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

#### 8.10. Відсортуйте ```df``` по-перше за віком в спадаючому порядку, по-друге за к-стю візитів в зростаючому порядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

#### 8.11. В ```'animal'``` ствобчику, змініть всіх ```'snake'``` на ```'python'```:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

## Scipy & Matplotlib

### 9. За допомогою scipy згенерувати та за допомогою matplotlib побудувати вибірки, правильно підписавши осі та назвавши графік з обраними відповідними параметрами:

#### 9.1. Виібрку з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.2. Вибірку з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.3. Вибірку з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.4. Вибірку з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```